# Generated by Django 5.0.7 on 2024-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('pin', models.IntegerField(null=True)),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('online_payment', 'online_payment')], default='online_payment', max_length=200, null=True)),
            ],
        ),
    ]
