# Generated by Django 5.0.7 on 2024-10-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
