# Generated by Django 5.0.7 on 2024-10-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_updated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='updated_price',
            field=models.IntegerField(null=True),
        ),
    ]
