# Generated by Django 5.0.7 on 2024-11-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_price',
        ),
    ]
