# Generated by Django 5.0.7 on 2024-11-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_updated_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('online_payment', 'online_payment')], default='online_payment', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
