# Generated by Django 5.0.7 on 2024-11-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_ordersummary_product_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='product_object',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
